### ISSUE TITLE
Can't start container after latest update

### ISSUE THREAD

**Issue by SuberSeb** [dnsforge-repo/xteve#1]
After latest update can't start container. Error:` /bin/sh: /home/xteve/bin/xteve_starter.pl: not found`

**Comment by AnnabellaRenee87** [comment]
Same issue here too.

**Comment by norrisp90** [comment]
See same here this morning, docker on unraid 6.8.3.

**Comment by Robsta86** [comment]
Same issue here, also on unraid 6.8.3
Due to not using tags other than :latest it's also not possible to redownload the previous build that was working 👎

**Comment by xteve-repo** [comment]
Greetings,
Either download the latest unraid template or edit the current template and ensure only the following "Container Paths"
are included in your current template.  The container will now start.

/mnt/user/appdata/xteve -> /home/xteve/conf
/mnt/user/appdata/xteve/guide2go/conf/ -> /home/xteve/guide2go/conf

![unknown](https://user-images.githubusercontent.com/58121321/87227642-6d8b0b00-c36a-11ea-8b6f-76b0662179e3.png)

**Comment by CanonCan** [comment]
I have those same container paths and mine still fails to start on Both unraid 6.8.3 and unraid 6.9 beta 24

**Comment by dnsforge-repo** [comment]
@CanonCan  Glad to hear your back up and running! Yes, removing the additional container path's will fix the issue.  The dnsforge Unraid template has also been fixed on the CA store.

**Comment by dnsforge-repo** [comment]
Unraid template was fixed.  No other issues were found.
