### ISSUE TITLE
Error adding schedules direct lineups with guide2conf

### ISSUE THREAD

**Issue by tobiasredel** [dnsforge-repo/xteve#14]
Hi, when trying to adding a lineup using guide2confi get the following error message:
2023/05/26 08:29:20 [ERROR] json: cannot unmarshal object into Go value of type []struct { Headend string "json:\"headend\""; Lineups []struct { Lineup string "json:\"lineup\""; Name string "json:\"name\""; URI string "json:\"uri\"" } "json:\"lineups\""; Location string "json:\"location\""; Transport string "json:\"transport\"" }

Is the guide2confscript outdated?

**Comment by dnsforge-repo** [comment]
No known issues with guide2conf @tobiasredel it could be specific to the lineup your trying to download via the SD API. Try another lineup.
