### ISSUE TITLE
Zap2xml tvguide stopped working

### ISSUE THREAD

**Issue by adgoncal** [dnsforge-repo/xteve#3]
I had this working for a few days, but I think tvguide changed their api in some way. I found other people with the same problem:
https://forums.nextpvr.com/showthread.php?tid=62192

I don't know if zap2xml.py is still maintained anywhere, but my best guess is it will require an update to work with tvguide again.

**Comment by dnsforge-repo** [comment]
Thanks @adgoncal, We are aware that the tvguide.com API is no longer working, and are monitoring the situation to see if they are going to support it in the future. In the meantime you can use zap2it (just use guide2conf and choose the "z" option) to create a zap lineup or optionally use Schedules DIrect (Both are supported in the dnsforge docker. If it becomes clear TVG are no longer going to support their API, we will remove it in a future update.

**Comment by dnsforge-repo** [comment]
tvguide.com service discontinued, support will be removed in v1.1.0
