### ISSUE TITLE
add xteve with vpn docker?

### ISSUE THREAD

**Issue by jscottdouglas** [dnsforge-repo/xteve#4]
I am dumb with dockers any chance of adding openvpn to this docker so that xteve connects thru VPN to streams?
your docker is used with cloudbox i would love for an xteve vpn cloudbox... i'd pay for this too.

**Comment by dnsforge-repo** [comment]
If you want to use dnsforge with a VPN, configure it to use a dedicated VPN container as its network in the docker run:

--net=container:<container_name>

There is not really any advantage to running openvpn in the actual container, and would add unnecessary complexity.

**Comment by chenks** [comment]
> I am dumb with dockers any chance of adding openvpn to this docker so that xteve connects thru VPN to streams? your docker is used with cloudbox i would love for an xteve vpn cloudbox... i'd pay for this too.

hi @jscottdouglas did you ever do this?
i currently have xteve running in a docker container on my synology NAS and would be interested in also connecting it via a VPN

**Comment by elmocito** [comment]
> > I am dumb with dockers any chance of adding openvpn to this docker so that xteve connects thru VPN to streams? your docker is used with cloudbox i would love for an xteve vpn cloudbox... i'd pay for this too.
> 
> hi @jscottdouglas did you ever do this? i currently have xteve running in a docker container on my synology NAS and would be interested in also connecting it via a VPN

not regarding to this ticket, but how did you figure out the file path?
<img width="521" alt="image" src="https://user-images.githubusercontent.com/42518790/179425542-cbe81760-d21e-488f-8360-e2d9f2a0ffd0.png">

**Comment by dnsforge-repo** [comment]
> > > I am dumb with dockers any chance of adding openvpn to this docker so that xteve connects thru VPN to streams? your docker is used with cloudbox i would love for an xteve vpn cloudbox... i'd pay for this too.
> > 
> > 
> > hi @jscottdouglas did you ever do this? i currently have xteve running in a docker container on my synology NAS and would be interested in also connecting it via a VPN
> 
> not regarding to this ticket, but how did you figure out the file path? I tried multiple options and went through folder by folder... Nothing works. <img alt="image" width="495" src="https://user-.githubusercontent.com/42518790/179427494-faf27a7e-7a3d-40d1-afe5-2ba0e8bfb08d.png">

xTeVe knows nothing about your synology, it cannot see the synology file system.  xTeVe expects a container path such as /home/xteve/conf/data/tvhd.m3u

**Comment by dnsforge-repo** [comment]
closed due to work around to provide vpn container via docker is available.

**Comment by chenks** [comment]
is there a recommended vpn container to use?
