### ISSUE TITLE
Update to xteve 2.2.0

### ISSUE THREAD

**Issue by barzog** [dnsforge-repo/xteve#5]
Xteve 2.2.0 is out on 29.03.2021. Pls update image.

**Comment by barzog** [comment]
In my setup (using podman) container is destroyed after stop and recreated on start from image. So this kind of 'in-container' update is valid only untill container restart. And after start it will be updated again. So, having latest xteve in container image is nice thing to have.

**Comment by kavemang** [comment]
Is this repo still active? Im finding I can map guides over 480 channels

**Comment by dnsforge-repo** [comment]
Yes, still active.  It is only Plex that has the 480 channel limit, its not a xTeVe limitation.

**Comment by steamyRayV** [comment]
In addition to what barzog said, I think it couldn't hurt to also update the Alpine base in the Docker image.
